/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Younouss boré
 */
public class Reglage_modification extends javax.swing.JFrame {

    /**
     * Creates new form Inscription
     */
    public static Info_user user1=new Info_user();
    public static Info_user user2=new Info_user();
    
    
    public Reglage_modification() {
        initComponents();
    }
    String urlBDD = "jdbc:mysql://localhost:3306/agencebd";
    String user = "root";
    String passwd = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inscription_nom_field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inscription_prenom_field = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inscription_email_field = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inscription_motdepasse_field = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inscription_tel_field = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        inscription_adresse_field = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        inscription_passport_field = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        inscription_motdepasseconfirme_field = new javax.swing.JPasswordField();
        inscription_genre_field = new javax.swing.JComboBox<>();
        modifier_btn_modifer = new javax.swing.JButton();
        Inscription_btn_reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(254, 184, 184));

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        jLabel2.setText("SWEET TRAVEL");
        jLabel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jLabel1.setText("Nom:");

        jLabel3.setText("Prenom:");

        inscription_prenom_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscription_prenom_fieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Email:");

        jLabel5.setText("Ancien mot de passe:");

        inscription_motdepasse_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscription_motdepasse_fieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Nouveau mot de passe:");

        jLabel7.setText("Tel:");

        jLabel8.setText("Adresse");

        jLabel9.setText("Numero Passe Port:");

        jLabel10.setText("Genre");

        inscription_genre_field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Homme", "Femme", "Non specifier" }));
        inscription_genre_field.setEnabled(false);
        inscription_genre_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscription_genre_fieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inscription_adresse_field, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inscription_tel_field, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inscription_email_field, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inscription_nom_field, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inscription_prenom_field, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inscription_motdepasse_field, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inscription_motdepasseconfirme_field, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inscription_genre_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inscription_passport_field, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inscription_nom_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inscription_prenom_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inscription_email_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inscription_motdepasse_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inscription_motdepasseconfirme_field, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inscription_tel_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inscription_adresse_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inscription_passport_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inscription_genre_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        modifier_btn_modifer.setBackground(new java.awt.Color(0, 204, 51));
        modifier_btn_modifer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        modifier_btn_modifer.setForeground(new java.awt.Color(255, 255, 255));
        modifier_btn_modifer.setText("Modifier");
        modifier_btn_modifer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifier_btn_modiferActionPerformed(evt);
            }
        });

        Inscription_btn_reset.setBackground(new java.awt.Color(204, 0, 51));
        Inscription_btn_reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Inscription_btn_reset.setForeground(new java.awt.Color(255, 255, 255));
        Inscription_btn_reset.setText("RESET");
        Inscription_btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inscription_btn_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(modifier_btn_modifer)
                        .addGap(176, 176, 176)
                        .addComponent(Inscription_btn_reset))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifier_btn_modifer)
                    .addComponent(Inscription_btn_reset))
                .addGap(0, 41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2KeyPressed

    private void modifier_btn_modiferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifier_btn_modiferActionPerformed
        // TODO add your handling code here:
        String nom=inscription_nom_field.getText();
        /*int contact_tel = Integer.parseInt(contact_tel_field.getText());*/
        String prenom=inscription_prenom_field.getText();
        String email=inscription_email_field.getText();
        String motdepasse=inscription_motdepasse_field.getText();
        String motdepasseconfirme=inscription_motdepasseconfirme_field.getText();
        String tel=inscription_tel_field.getText();
        String adresse=inscription_adresse_field.getText();
        String passport=inscription_passport_field.getText();
        //COnnexion avec la base
        
        String urlBDD = "jdbc:mysql://localhost:3306/agencebd";
        String user = "root";
        String passwd = "";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection(urlBDD, user, passwd);
            System.out.println("connexion reussi mec");
            String requete_verification="SELECT * FROM user WHERE email=?;";
            PreparedStatement state_verification= conn.prepareStatement(requete_verification);
            state_verification.setString(1, email);
            
            ResultSet result_verificaion=state_verification.executeQuery();            
            //contact
            String requete_user="UPDATE `contact` SET `email` =?, `tel` = ?, `adresse` = ? WHERE `contact`.`id` = ?";
            PreparedStatement state= conn.prepareStatement(requete_user);
            state.setString(1, email);
            state.setString(2, tel);
            state.setString(3, adresse);
            state.setString(4, Info_user.idcontact);
            int result=state.executeUpdate();
            //client
            String requete_client="UPDATE `client` SET `nom`=?, `prenom`=?, `passport`=? WHERE `client`.`id`=?;";
            state= conn.prepareStatement(requete_client);
            state.setString(1, nom);
            state.setString(2, prenom);
            state.setString(3, passport);
            state.setString(4, Info_user.idclient);
            result=state.executeUpdate();

            //user
            requete_client="UPDATE `user` SET `nom`=?, `prenom`=?, `email`=?, `motdepasse`=? WHERE `user`.`id`=?;";
            state= conn.prepareStatement(requete_client);
            state.setString(1, nom);
            state.setString(2, prenom);
            state.setString(3, email);
            state.setString(4, motdepasseconfirme);
            state.setString(5, Info_user.idclient);
            result=state.executeUpdate();

            JOptionPane.showMessageDialog(this, "Modification Reussi"+ nom, "Ajout reussi", JOptionPane.INFORMATION_MESSAGE);
            Info_user.nom=nom;
            Info_user.prenom=prenom;
            Info_user.email=email;
            Info_user.motdepasse=motdepasseconfirme;
            Info_user.tel=tel;
            Info_user.adresse=adresse;
            Info_user.passeport=passport;
            System.out.println("votre id est:"+Info_user.idclient+"\net votre nom est: "+Info_user.nom+"\nvotre prenom est:"+Info_user.prenom+"\nVotre email est: "+Info_user.email+"Votre mot de passe est: "+Info_user.motdepasse);
            System.out.println("votre genre est:"+Info_user.genre+"\net votre passeport est: "+Info_user.passeport);
            System.out.println("votre tel est:"+Info_user.tel+"\net votre adresse est: "+Info_user.adresse);  
            this.dispose();
        }
        catch (Exception e){
            e.printStackTrace();
            System.out.println("Erreur de connexion");
        }
        
    }//GEN-LAST:event_modifier_btn_modiferActionPerformed

    private void Inscription_btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inscription_btn_resetActionPerformed
        // TODO add your handling code here:
        
        inscription_nom_field.setText("");
        inscription_prenom_field.setText("");
        inscription_email_field.setText("");
        inscription_motdepasse_field.setText("");
        inscription_motdepasseconfirme_field.setText("");
        inscription_tel_field.setText("");
        inscription_adresse_field.setText("");
        inscription_passport_field.setText("");
    }//GEN-LAST:event_Inscription_btn_resetActionPerformed

    private void inscription_prenom_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscription_prenom_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inscription_prenom_fieldActionPerformed

    private void inscription_motdepasse_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscription_motdepasse_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inscription_motdepasse_fieldActionPerformed

    private void inscription_genre_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscription_genre_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inscription_genre_fieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reglage_modification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reglage_modification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reglage_modification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reglage_modification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reglage_modification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Inscription_btn_reset;
    private javax.swing.JTextField inscription_adresse_field;
    private javax.swing.JTextField inscription_email_field;
    private javax.swing.JComboBox<String> inscription_genre_field;
    private javax.swing.JTextField inscription_motdepasse_field;
    private javax.swing.JPasswordField inscription_motdepasseconfirme_field;
    private javax.swing.JTextField inscription_nom_field;
    private javax.swing.JTextField inscription_passport_field;
    private javax.swing.JTextField inscription_prenom_field;
    private javax.swing.JTextField inscription_tel_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton modifier_btn_modifer;
    // End of variables declaration//GEN-END:variables
}
